[workspace]
resolver = "2"
members = [
    "examples/basic",
    "examples/client",
    "examples/authenticating",
    "privileged_helper_tool"
]

[workspace.dependencies]
tokio = { version = "1.36.0" }
