[package]
name = "authenticating"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
privileged_helper_tool = { path = "../../privileged_helper_tool" }
tokio = { version = "1.3", features = ["io-util", "macros", "net", "rt"] }
